name: Testar SWAPI - Pessoas

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-pessoas:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Instalar dependências
        run: npm install

      - name: Executar testes de pessoas
        run: npm test tests/swapi.People.test.js
