name: Testes da SWAPI - Planetas

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-planets:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes de planetas
        run: npm test tests/swapi.Planets.test.js
