name: Testar Naves Estelares da SWAPI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-starships:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Instalar dependências
        run: npm install

      - name: Executar testes de naves estelares
        run: npm test tests/swapi.Starships.test.js
