name: Teste de Validação de Esquema da SWAPI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-schema-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes de validação de esquema
        run: npm test tests/swapi.SchemaValidation.test.js
