name: Teste de Filmes SWAPI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-films:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Instalar dependências
        run: npm install

      - name: Executar testes de filmes
        run: npm test tests/swapi.Films.test.js
